/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_C;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JOptionPane;

/**
 *
 * @author Azka
 */
public class PenampilGambar extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambar
     */
    public PenampilGambar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPanel = new javax.swing.JPanel();
        ShibuyaBtn = new javax.swing.JButton();
        FujiyamaBtn = new javax.swing.JButton();
        InariBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        PictPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Showing Picture Apps");
        setUndecorated(true);

        ShibuyaBtn.setText("Shibuya Street");
        ShibuyaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShibuyaBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(ShibuyaBtn);

        FujiyamaBtn.setText("Fujiyama");
        FujiyamaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FujiyamaBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(FujiyamaBtn);

        InariBtn.setText("Fushimi Inari Taisha");
        InariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InariBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(InariBtn);

        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        BtnPanel.add(ExitBtn);

        getContentPane().add(BtnPanel, java.awt.BorderLayout.PAGE_START);

        PictPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_C/Shibuya.jpg"))); // NOI18N
        PictPanel.add(jLabel1, "0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_C/Fujiyama.jpg"))); // NOI18N
        PictPanel.add(jLabel2, "1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI_C/Fushimi Inari Taisha.jpg"))); // NOI18N
        PictPanel.add(jLabel3, "2");

        getContentPane().add(PictPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShibuyaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShibuyaBtnActionPerformed
        // TODO add your handling code here:
        CardLayout Cl = (CardLayout)(PictPanel.getLayout());
        Cl.show(PictPanel,"0");
    }//GEN-LAST:event_ShibuyaBtnActionPerformed

    private void FujiyamaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FujiyamaBtnActionPerformed
        // TODO add your handling code here:
        CardLayout Cl = (CardLayout)(PictPanel.getLayout());
        Cl.show(PictPanel,"1");
    }//GEN-LAST:event_FujiyamaBtnActionPerformed

    private void InariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InariBtnActionPerformed
        // TODO add your handling code here:
        CardLayout Cl = (CardLayout)(PictPanel.getLayout());
        Cl.show(PictPanel,"2");
    }//GEN-LAST:event_InariBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showConfirmDialog(this, "Apakah Anda Ingin Keluar ?");
       if(jawab == JOptionPane.YES_OPTION){
          System.exit(0);
       }
    }//GEN-LAST:event_ExitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                          
                new PenampilGambar().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton FujiyamaBtn;
    private javax.swing.JButton InariBtn;
    private javax.swing.JPanel PictPanel;
    private javax.swing.JButton ShibuyaBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
